contact_links:
  - name: OpenSearch Community Support
    url: https://forum.opensearch.org
    about: Please ask and answer questions here.
  - name: AWS/Amazon Security
    url: https://aws.amazon.com/security/vulnerability-reporting/
    about: Please report security vulnerabilities here.